[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"

# Настраиваем постоянное хранилище для базы данных
[volumes]
data = "/app/data"

[variables]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "true"